### ISSUE TITLE
Confusion over the trailer folder

### ISSUE THREAD

**Issue by davecburke** [nandyalu/trailarr#14]
I might be confused about how Trailarr works but I thought the aim of it is to create a Trailers folder in the show/movie folders. So if I had a path of /mnt/media/tv/my_tv_show that sonarr populates, Trailarr would create /mnt/media/tv/my_tv_show/Trailers/trailer.mkv for example. Trailarr is downloading trailers but storing then locally i.e ~/docker/trailarr/appdata/media/tv/Sunny/Trailers. This is my docker compose:
```
services:
  trailarr:
    image: nandyalu/trailarr:latest
    container_name: trailarr
    environment:
      - TZ=Australia/Melbourne
    ports:
      - 7889:7889
    volumes:
      - ./appdata:/data
      - /mnt/data/media/movies:/mnt/data/media/movies
      - /mnt/data/media/tv:/mnt/data/media/tv
    restart: on-failure
```
Thanks for any help

**Comment by nandyalu** [comment]
what is the actual volume mapping for `Radarr`/`Sonarr`?

**Comment by davecburke** [comment]
Radarr is /mnt/data/media/movies and Sonarr is /mnt/data/media/tv so they do match

**Comment by nandyalu** [comment]
Can you open app in a browser, go to the movie/show where a trailer was downloaded to container folder and post a screenshot showing the media path and also the files (you can mask actual media files if you want)?

**Comment by davecburke** [comment]
![trailarr](https://github.com/user-attachments/assets/33516a56-75ea-47b0-a855-c9784acfb26d)
![trailarr2](https://github.com/user-attachments/assets/6de9bc90-8fd3-478f-a06c-27874021b856)

**Comment by nandyalu** [comment]
App saves trailer to the Media folder, so can you post the screenshot showing path of that media?

**Comment by davecburke** [comment]
Isn't this the path to the media folder that I posted yesterday?
![356143053-6de9bc90-8fd3-478f-a06c-27874021b856](https://github.com/user-attachments/assets/40bfc9ec-c8af-4b22-bc3c-50275d256874)

**Comment by nandyalu** [comment]
Please post a screenshot of the media details page showing path like this:
![image](https://github.com/user-attachments/assets/ffbb11b2-3cdd-4d52-a99b-e7b646ce93a1)

**Comment by davecburke** [comment]
![trailarr3](https://github.com/user-attachments/assets/a4d722fc-e721-4b1c-8d16-e908ddc07ae1)

**Comment by nandyalu** [comment]
Looks like there might be a problem with your compose config. Can you post you `Radarr` and `Sonarr` docker compose?

**Comment by davecburke** [comment]
```
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Melbourne
    volumes:
      - ./config:/config
      - /mnt/data:/data #optional
      # - /path/to/download-client-downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
```

```
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Melbourne
    volumes:
      - ./config:/config
      - /mnt/data:/data #optional
      #- /mnt/media/Downloads:/data #optional
    ports:
      - 8989:8989
    restart: unless-stopped
```

**Comment by nandyalu** [comment]
you need to add the same volume mappings for media folders from your `Radarr` and `Sonarr` to `Trailarr`. However since both of them point to `/data` inside `Radarr/Sonarr` containers, this doesn't work.

If you had those mapped to some other folders than `/data` you would've been able to use 2 instances of `Trailarr` to make it work.

## Based on an assumption
Based on media path from comment https://github.com/nandyalu/trailarr/issues/14#issuecomment-2277010853, I am assuming that your local folder paths are `/mnt/data/media/movies` and `/mnt/data/media/tv`. If that is the case then you can map use below `docker compose` to make it work!

```yaml
services:
  trailarr:
    image: nandyalu/trailarr:latest
    container_name: trailarr
    environment:
      - TZ=Australia/Melbourne
    ports:
      - 7889:7889
    volumes:
      - ./appdata:/data
      - /mnt/data/media/movies:/data/media/movies
      - /mnt/data/media/tv:/data/media/tv
    restart: on-failure
```

or simply the volumes a little bit more like:

```yaml
services:
  trailarr:
    image: nandyalu/trailarr:latest
    container_name: trailarr
    environment:
      - TZ=Australia/Melbourne
    ports:
      - 7889:7889
    volumes:
      - ./appdata:/data
      - /mnt/data/media:/data/media
    restart: on-failure
```
