### ISSUE TITLE
Add ability to change the '/data' directory to another one, for example '/config'

### ISSUE THREAD

**Issue by sunrize** [nandyalu/trailarr#21]
**Is your feature request related to a problem? Please describe.**
I had the same problem as in #14 and applied the same solution as in your [comment](https://github.com/nandyalu/trailarr/issues/14#issuecomment-2277087222), but it creates "ghost" directories inside `appdata` on the container host. Furthermore containers from [LinuxServer.io](https://docs.linuxserver.io/images/docker-sonarr/) and [hotio.dev](https://hotio.dev/containers/sonarr/) use `/config` path for application files and I would like to apply the same approach for Trailarr.

**Describe the solution you'd like**
Create an `APP_DATA` environment variable to specify the path for the Trailarr files. If it is not specified, then use the default path `/data`.

**Describe alternatives you've considered**
When [path mapping](https://github.com/nandyalu/trailarr/milestone/3) is implemented, I assume that I will be able to mount the Sonarr and Radarr media folders under `/media` and redirect their paths there, that is, it will not interfere with `/data`.

**Additional context**
Right now my `docker-compose.yml` looks something like this:
```yaml
services:
  ...
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    volumes:
      - /docker/appdata/sonarr:/config
      - /mnt/data:/data  # sonarr root folder /data/media/series
    ports:
      - 8989:8989
    restart: unless-stopped
  trailarr:
    image: nandyalu/trailarr:latest
    container_name: trailarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    ports:
      - 7889:7889
    volumes:
      - /docker/appdata/trailarr:/data
      - /mnt/data/media:/data/media  # this creates 'ghost' subdirectories under /docker/appdata/trailarr on the host
    restart: on-failure
  ...
```

With `APP_DATA` environment variable, it will look like this:
```yaml
services:
  ...
  trailarr:
    image: nandyalu/trailarr:latest
    container_name: trailarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
      - APP_DATA=/config
    ports:
      - 7889:7889
    volumes:
      - /docker/appdata/trailarr:/config 
      - /mnt/data/media:/data/media
    restart: on-failure
  ...
```
