### ISSUE TITLE
[Bug] Trailarr downloading multiple trailers and not seeing trailers that do exist

### ISSUE THREAD

**Issue by geebru** [nandyalu/trailarr#61]
**Describe the bug**

Trailarr was running for about 3 hours and it (seemingly) correctly downloaded trailers (a single `{title}.trailer.mp4` for a lot of movies (over 100).

At some point, Trailarr began downloading duplicate trailers. I stopped the container after it did this for about 15 media files.

The only clue is that the App doesn't seem to "see" _any_ of the work it's been doing. If I navigate to Home or Movies, only 4 movies are marked as having a trailer, despite me seeing Trailarr having added those hundred or more already today. Even in folders updated in this time span, showing a trailer.mp4 file, Trailarr still indicates they are "missing", despite a trailarr file being present.

_I'm ignoring all the created image assets as I believe those are from Jellyfin seeing the new file as an actual "movie" and not just a trailer. That may be resolved by me updating Trailarr to use a folder instead of `{title}.trailer.mp4` despite it claiming that is allowed._

Compose:
```yaml
  trailarr:
    image: nandyalu/trailarr:latest
    container_name: trailarr
    environment:
      - TZ=America/New_York
      - PUID=99
      - PGID=100
      - APP_DATA_DIR=/config
    ports:
      - 7889:7889
    volumes:
      - /mnt/cache/appdata/trailarr:/config
      - /mnt/user/data:/data
    network_mode: bridge
    restart: unless-stopped
```

**Steps To Reproduce**
1. Add Radarr connection.
2. Set Radarr to fill in "Missing" trailers.
3. Run the download job.
4. Duplicates?

I know this isn't very helpful replication steps, but I set it up per the guides, and it's "working" but it seems to be doing extra things on top of that.

**Actual behavior**
Trailers are being downloaded multiple times and image assets are being duplicated.

**Expected behavior**
A single `{title}.trailer.mp4` should be downloaded.

**Screenshots**
These are the impacted films in case their titling gives any clues:
![List of movies impacted by bug](https://github.com/user-attachments/assets/21dc4b1b-4b2d-44a1-94cd-1d1144af9bb6)

Trailarr settings:
![Trailarr settings](https://github.com/user-attachments/assets/136cd5d6-5e75-45c3-983b-ac14c1a82f91)

Trailarr Home missing all of the successful grabs:
![Trailarr movies view](https://github.com/user-attachments/assets/0abe8eec-e840-4f44-8639-34f5acbc6081)

![21 Jump Street media folder](https://github.com/user-attachments/assets/6d9471bf-250a-4cc3-ab53-6f6c62bf7530)

![21 Jump Street duplicate in Jellyfin](https://github.com/user-attachments/assets/98a3adf1-586a-43b7-9c08-1cdcc03d4402)

![21 Jump Street duplicate is a trailer](https://github.com/user-attachments/assets/03813598-607a-412c-a3d9-5c858889d1a0)

![21 Jump Street in Trailarr marked as missing despite trailers being in the files](https://github.com/user-attachments/assets/ee68fcfd-4232-45f6-8dee-87ee375f08b8)

**App Information (please complete the following information):**
 - Unraid 6.12.13
 - Trailarr v0.2.1-beta

**Additional context**
I started down this as I realized I had set up my app config wrong, and despite Trailarr originally downloading a lot of trailers for me, they were all in `mnt/cache/appdata` and not in the media folders. I remedied that issue, but I am having this new issue instead.
